<a href="https://colab.research.google.com/github/ravindravala/AI/blob/main/customer_personality_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [91]:
import kagglehub

path = kagglehub.dataset_download("imakash3011/customer-personality-analysis")
print(path)

Using Colab cache for faster access to the 'customer-personality-analysis' dataset.
/kaggle/input/customer-personality-analysis

In [92]:
import pandas as pd
import os

file_path = os.path.join(path, "marketing_campaign.csv")

df = pd.read_csv(file_path, sep="\t")

In [93]:
df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,7,0,0,0,0,0,0,3,11,1

In [94]:
df = df.drop(columns=["Z_CostContact", "Z_Revenue","ID"],axis=1)

In [95]:
df

,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,...,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response
0,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,88,...,10,4,7,0,0,0,0,0,0,1
1,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,1,...,1,2,5,0,0,0,0,0,0,0
2,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,49,...,2,10,4,0,0,0,0,0,0,0
3,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,4,...,0,4,6,0,0,0,0,0,0,0
4,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,43,...,3,6,5,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,43,...,3,4,5,0,0,0,0,0,0,0
2236,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,0,...,2,5,7,0,0,0,1,0,0,0
2237,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,48,...,3,13,6,0,1,0,0,0,0,0
2238,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,30,...,5,10,3,0,0,0,0,0,0,0
2239,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,3,...,1,4,7,0,0,0,0,0,0,1

In [96]:
df['Year_Birth'] = 2026 - df['Year_Birth']

In [97]:
df["age"] = df["Year_Birth"]
df.drop("Year_Birth", axis=1, inplace=True)

In [98]:
df

,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,...,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,age
0,Graduation,Single,58138.0,0,0,04-09-2012,58,635,88,546,...,4,7,0,0,0,0,0,0,1,69
1,Graduation,Single,46344.0,1,1,08-03-2014,38,11,1,6,...,2,5,0,0,0,0,0,0,0,72
2,Graduation,Together,71613.0,0,0,21-08-2013,26,426,49,127,...,10,4,0,0,0,0,0,0,0,61
3,Graduation,Together,26646.0,1,0,10-02-2014,26,11,4,20,...,4,6,0,0,0,0,0,0,0,42
4,PhD,Married,58293.0,1,0,19-01-2014,94,173,43,118,...,6,5,0,0,0,0,0,0,0,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,Graduation,Married,61223.0,0,1,13-06-2013,46,709,43,182,...,4,5,0,0,0,0,0,0,0,59
2236,PhD,Together,64014.0,2,1,10-06-2014,56,406,0,30,...,5,7,0,0,0,1,0,0,0,80
2237,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,48,217,...,13,6,0,1,0,0,0,0,0,45
2238,Master,Together,69245.0,0,1,24-01-2014,8,428,30,214,...,10,3,0,0,0,0,0,0,0,70
2239,PhD,Married,52869.0,1,1,15-10-2012,40,84,3,61,...,4,7,0,0,0,0,0,0,1,72

In [99]:
df.dropna(inplace=True)

In [100]:
x = df.drop(["Response","Dt_Customer"], axis=1)
y = df["Response"]

In [101]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [102]:
categorical_cols = [
    'Education',
    'Marital_Status'
]

In [103]:
numeric_cols = [
    'Income',
    'Kidhome',
    'Teenhome',
    'Recency',
    'MntWines',
    'MntFruits',
    'MntMeatProducts',
    'MntFishProducts',
    'MntSweetProducts',
    'MntGoldProds',
    'NumDealsPurchases',
    'NumWebPurchases',
    'NumCatalogPurchases',
    'NumStorePurchases',
    'NumWebVisitsMonth',
    'AcceptedCmp3',
    'AcceptedCmp4',
    'AcceptedCmp5',
    'AcceptedCmp1',
    'AcceptedCmp2',
    'Complain',
    'age'
]

In [104]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(),numeric_cols),
        ("cat", OneHotEncoder(),categorical_cols)
    ]
)

In [105]:
x = preprocessor.fit_transform(x)

In [106]:
y = y.values

In [107]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [108]:
from torch.utils.data import DataLoader,Dataset

In [109]:
class CustomerDataset(Dataset):
    def __init__(self, x, y):
        self.x = torch.tensor(x, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

In [110]:
train_dataset = CustomerDataset(x_train, y_train)
test_dataset = CustomerDataset(x_test, y_test)
#

In [111]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [112]:
import torch
import torch.nn as nn
import torch.optim as optim

In [113]:
model = nn.Sequential(
    nn.Linear(x_train.shape[1],128),
    nn.ReLU(),
    nn.Linear(128,64),
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(64,1)
)

In [114]:
optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.BCEWithLogitsLoss()

In [115]:
epochs = 20

for epoch in range(epochs):

    total_loss = 0.0
    for x, y in train_loader:   # ✅ FIX

        optimizer.zero_grad()

        y_pred = model(x)

        y = y.unsqueeze(1)  # ensure correct shape

        loss = criterion(y_pred, y)

        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss/len(train_loader)}")

Epoch 1, Loss: 0.465139575568693
Epoch 2, Loss: 0.3098705569282174
Epoch 3, Loss: 0.28177531542522566
Epoch 4, Loss: 0.26561445623104063
Epoch 5, Loss: 0.2556258928296821
Epoch 6, Loss: 0.25069982119436773
Epoch 7, Loss: 0.23586929908820561
Epoch 8, Loss: 0.23173255273806198
Epoch 9, Loss: 0.22791881593210356
Epoch 10, Loss: 0.2202004562797291
Epoch 11, Loss: 0.2118262437039188
Epoch 12, Loss: 0.2010321587856327
Epoch 13, Loss: 0.19624203177435057
Epoch 14, Loss: 0.18843423721513577
Epoch 15, Loss: 0.18252191792375275
Epoch 16, Loss: 0.17445357556321792
Epoch 17, Loss: 0.16978169385609881
Epoch 18, Loss: 0.16356645803898573
Epoch 19, Loss: 0.15443708328530192
Epoch 20, Loss: 0.14782380984563911

In [116]:
model.eval()
with torch.no_grad():
    correct = 0
    total = 0

    for x, y in test_loader:
        y_pred = model(x)

        y_pred = torch.sigmoid(y_pred)
        y_pred = torch.round(y_pred)

        y = y.unsqueeze(1)   # ✅ FIX

        total += y.size(0)
        correct += (y_pred == y).sum().item()

    print(f"Test Accuracy: {100 * correct / total:.2f}%")

Test Accuracy: 90.09%