<a href="https://colab.research.google.com/github/ravindravala/AI/blob/main/Decease_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [134]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "healthcare_dataset.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "prasad22/healthcare-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

/tmp/ipykernel_350/2193524086.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'healthcare-dataset' dataset.

In [135]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [136]:
y = df["Test Results"]

In [137]:
y = y.map({"Normal": 0, "Inconclusive": 1, "Abnormal": 2})

In [138]:
df = df.drop("Test Results", axis=1)

In [139]:
# Convert dates
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])

# Create stay length
df["Stay Length"] = (df["Discharge Date"] - df["Date of Admission"]).dt.days

# Drop useless columns
df = df.drop([
    "Name",
    "Doctor",
    "Hospital",
    "Room Number",
    "Date of Admission",
    "Discharge Date"
], axis=1)

# Encode categorical columns
df = pd.get_dummies(df, drop_first=True)

print(df.shape)
print(df.columns)

(55500, 26)
Index(['Age', 'Billing Amount', 'Stay Length', 'Gender_Male', 'Blood Type_A-',
       'Blood Type_AB+', 'Blood Type_AB-', 'Blood Type_B+', 'Blood Type_B-',
       'Blood Type_O+', 'Blood Type_O-', 'Medical Condition_Asthma',
       'Medical Condition_Cancer', 'Medical Condition_Diabetes',
       'Medical Condition_Hypertension', 'Medical Condition_Obesity',
       'Insurance Provider_Blue Cross', 'Insurance Provider_Cigna',
       'Insurance Provider_Medicare', 'Insurance Provider_UnitedHealthcare',
       'Admission Type_Emergency', 'Admission Type_Urgent',
       'Medication_Ibuprofen', 'Medication_Lipitor', 'Medication_Paracetamol',
       'Medication_Penicillin'],
      dtype='object')

In [140]:
df

,Age,Billing Amount,Stay Length,Gender_Male,Blood Type_A-,Blood Type_AB+,Blood Type_AB-,Blood Type_B+,Blood Type_B-,Blood Type_O+,...,Insurance Provider_Blue Cross,Insurance Provider_Cigna,Insurance Provider_Medicare,Insurance Provider_UnitedHealthcare,Admission Type_Emergency,Admission Type_Urgent,Medication_Ibuprofen,Medication_Lipitor,Medication_Paracetamol,Medication_Penicillin
0,30,18856.281306,2,True,False,False,False,False,True,False,...,True,False,False,False,False,True,False,False,True,False
1,62,33643.327287,6,True,False,False,False,False,False,False,...,False,False,True,False,True,False,True,False,False,False
2,76,27955.096079,15,False,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,28,37909.782410,30,False,False,False,False,False,False,True,...,False,False,True,False,False,False,True,False,False,False
4,43,14238.317814,20,False,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,42,2650.714952,30,False,False,False,False,False,False,True,...,True,False,False,False,False,False,False,False,False,True
55496,61,31457.797307,9,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
55497,38,27620.764717,28,False,False,False,False,True,False,False,...,False,False,False,True,False,True,True,False,False,False
55498,43,32451.092358,6,True,False,False,False,False,False,False,...,False,False,True,False,False,False,True,False,False,False
55499,53,4010.134172,27,False,False,False,False,False,False,True,...,False,False,False,False,False,True,True,False,False,False

In [141]:
split = int(len(df) * 0.8)
print(split)

44400

In [142]:
x_train = df.iloc[:split]
y_train = y[:split]
x_test = df.iloc[split:]
y_test = y[split:]

In [143]:
from torch.utils.data import DataLoader, Dataset

In [144]:
import torch
from torch.utils.data import Dataset

class CustomDataset(Dataset):

    def __init__(self, x, y):
        self.x = torch.tensor(x.values, dtype=torch.float32)
        self.y = torch.tensor(y.values, dtype=torch.long)

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

In [145]:
import torch.nn as nn
import torch.optim as optim
import torch

In [146]:
model = nn.Sequential(
    nn.Linear(26, 64),
    nn.ReLU(),
    nn.Linear(64, 3)
)

In [147]:
loss_function = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [148]:
x_train = x_train.astype(float)
y_train = y_train.astype(float)
x_test = x_test.astype(float)
y_train = y_train.astype(float)

In [149]:
train_dataset = CustomDataset(x_train, y_train)
test_dataset = CustomDataset(x_test, y_test)

In [150]:
train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=64
)

In [151]:
print(x_train.values.dtype)

float64

In [152]:
for epoch in range(30):

    total_loss = 0

    for X_batch, y_batch in train_loader:

        outputs = model(X_batch)

        loss = loss_function(outputs, y_batch)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)

    print("Epoch", epoch, "| Loss:", avg_loss)

Epoch 0 | Loss: 50.57730676907971
Epoch 1 | Loss: 20.723159245352235
Epoch 2 | Loss: 20.5780707319463
Epoch 3 | Loss: 17.194780310224044
Epoch 4 | Loss: 16.41757769698025
Epoch 5 | Loss: 17.059976059352973
Epoch 6 | Loss: 14.751478600055409
Epoch 7 | Loss: 15.083439655537564
Epoch 8 | Loss: 15.561184218190933
Epoch 9 | Loss: 13.505835664375372
Epoch 10 | Loss: 15.021719630582188
Epoch 11 | Loss: 15.702304001672124
Epoch 12 | Loss: 13.198867874289796
Epoch 13 | Loss: 11.612481500642101
Epoch 14 | Loss: 10.11481326784112
Epoch 15 | Loss: 10.918818271812857
Epoch 16 | Loss: 8.82776249691801
Epoch 17 | Loss: 9.759292013019925
Epoch 18 | Loss: 8.10285235241442
Epoch 19 | Loss: 8.746596441832331
Epoch 20 | Loss: 6.807623129413176
Epoch 21 | Loss: 7.077099532833704
Epoch 22 | Loss: 7.307733185009585
Epoch 23 | Loss: 7.465620372755727
Epoch 24 | Loss: 6.331020810762125
Epoch 25 | Loss: 5.509686030812497
Epoch 26 | Loss: 5.48393272752377
Epoch 27 | Loss: 5.703989513669303
Epoch 28 | Loss: 6.212317490612052
Epoch 29 | Loss: 5.501318695909352

In [153]:
correct = 0
total = 0

with torch.no_grad():

    for X_batch, y_batch in test_loader:

        outputs = model(X_batch)

        preds = torch.argmax(outputs, dim=1)

        correct += (preds == y_batch).sum().item()
        total += y_batch.size(0)

print("Accuracy:", correct / total)

Accuracy: 0.3363063063063063